[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
# The primary colors for the terminal window
background = '#0a0f09'
foreground = '#95ff80'

[colors.cursor]
text = 'CellBackground'
cursor = 'CellForeground'

[colors.normal]
# Normal colors used by applications
black = '#050804'
red = '#FF5555'
green = '#95FF80'
blue = '#6EBF5D'
magenta = '#7BCF6B'
cyan = '#62A058'
white = '#95FF80'
yellow = '#487041'

[colors.bright]
# Bright colors used for emphasis
black = '#95FF80'
red = '#FF5555'
green = '#BDE0FE'
yellow = '#6EBF5D'
blue = '#7BCF6B'
magenta = '#62A058'
cyan = '#487041'
white = '#95FF80'
